### ISSUE TITLE
2.5: Collection URL is not valid

### ISSUE THREAD

**Issue by azrek** [catalyst/moodle-assignsubmission-mahara#11]
Hi,

Working with the 2.5 pluging and Moodle 2.5, when a student submits a collection as a draft, if you click on the image next to the collection (i.e. the search icon), the URL is invalid:

http://d.mahara/http://d.mahara/view/view.php?id=15

It should be: 
http://d.mahara/view/view.php?id=15

To recreate:
- Student submits a collection
- Teacher 'Revert submission to draft'
- Student 'Edit submission' and select another page (as draft). Save changes.
- Student 'Edit submission' and select the collection again (as draft). Save changes.
- Click on the collection icon to view it, get invalid URL.

After the student submits assignment, the URL is correct.

Thanks.

**Comment by danmarsden** [comment]
closing this one - issues have now moved to: https://github.com/MaharaProject/moodle-assignsubmission-mahara/issues
