### ISSUE TITLE
2.6-merged: submitted page/collection

### ISSUE THREAD

**Issue by azrek** [catalyst/moodle-assignsubmission-mahara#14]
I can get some weirdness happening with the submission of a collection.  

To replicate:
- Create a Mahara assignment (where user can save as draft before sumitting assignment)
- Log into Moodle as student and add a collection but do not submit assignment.
- In Mahara as the student, submit that same collection to a group.
- In Moodle as the teacher, select 'Prevent submission changes' for that student.
- This will result in the error message that this collection is already submitted, etc... (which is correct).
- But, the student is now not allowed to make any more submissions and the teacher can actually view the collection.  

In this particular situtation, the teacher had placed a grade previously - while I was playing with enable/prevent submission changes.

In Mahara, the group can now release the collection and the student can modify it.

I think I can also do this using the 2.6 branch.  Didn't test this case in 2.3, 2.4, and 2.5.

**Comment by danmarsden** [comment]
closing this one - issues have now moved to: https://github.com/MaharaProject/moodle-assignsubmission-mahara/issues
