### ISSUE TITLE
2.6-merged: undefined property stdClass::$viewid

### ISSUE THREAD

**Issue by azrek** [catalyst/moodle-assignsubmission-mahara#15]
I'm getting the following notification:

Notice: Undefined property: stdClass::$viewid in /var/www/moodle/moodle/mod/assign/submission/mahara/locallib.php on line 388 Call Stack: 0.0029 665848 1. {main}() /var/www/moodle/moodle/mod/assign/view.php:0 0.3704 59637696 2. assign->view(???) /var/www/moodle/moodle/mod/assign/view.php:53 0.3704 59638808 3. assign->process_save_submission(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:384 0.6820 63210464 4. assign->save_submission(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:5473 0.6866 63212312 5. assign_submission_mahara->save(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:5379 Notice: Undefined property: stdClass::$viewid in /var/www/moodle/moodle/mod/assign/submission/mahara/locallib.php on line 391 Call Stack: 0.0029 665848 1. {main}() /var/www/moodle/moodle/mod/assign/view.php:0 0.3704 59637696 2. assign->view(???) /var/www/moodle/moodle/mod/assign/view.php:53 0.3704 59638808 3. assign->process_save_submission(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:384 0.6820 63210464 4. assign->save_submission(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:5473 0.6866 63212312 5. assign_submission_mahara->save(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:5379 Notice: Undefined property: stdClass::$viewid in /var/www/moodle/moodle/mod/assign/submission/mahara/locallib.php on line 392 Call Stack: 0.0029 665848 1. {main}() /var/www/moodle/moodle/mod/assign/view.php:0 0.3704 59637696 2. assign->view(???) /var/www/moodle/moodle/mod/assign/view.php:53 0.3704 59638808 3. assign->process_save_submission(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:384 0.6820 63210464 4. assign->save_submission(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:5473 0.6866 63212312 5. assign_submission_mahara->save(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:5379 Warning: array_key_exists(): The first argument should be either a string or an integer in /var/www/moodle/moodle/mod/assign/submission/mahara/locallib.php on line 432 Call Stack: 0.0029 665848 1. {main}() /var/www/moodle/moodle/mod/assign/view.php:0 0.3704 59637696 2. assign->view(???) /var/www/moodle/moodle/mod/assign/view.php:53 0.3704 59638808 3. assign->process_save_submission(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:384 0.6820 63210464 4. assign->save_submission(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:5473 0.6866 63212312 5. assign_submission_mahara->save(???, ???) /var/www/moodle/moodle/mod/assign/locallib.php:5379 0.9175 63334720 6. array_key_exists(???, ???) /var/www/moodle/moodle/mod/assign/submission/mahara/locallib.php:432

To reproduce:
- Create a Mahara assignment (with drafts) in Moodle.
- As a student, login to Mahara and create 2 pages and a collection with one of the pages.
- In Moodle as the student, display the screen to edit submission (i.e. 1 page and 1 collection displays).
- In **another** window as that same student, in Mahara, submit the page to a group.
- In Moodle as the student (in the first window), select the page and save changes.
- Will produce the above notification.

**Comment by danmarsden** [comment]
closing this one - issues have now moved to: https://github.com/MaharaProject/moodle-assignsubmission-mahara/issues
