### ISSUE TITLE
On a multi-type assignment, check whether the user has any views or collections

### ISSUE THREAD

**Issue by agwells** [catalyst/moodle-assignsubmission-mahara#8]
If you set up a multi-type assignment, and the user has no views or collections (and thus has saved none), the plugin crashes. See https://mahara.org/interaction/forum/topic.php?id=6382

**Comment by danmarsden** [comment]
closing this one - issues have moved to: https://github.com/MaharaProject/moodle-assignsubmission-mahara/issues
